<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>promises</title>
</head>
<body>
    
</body>
<script>
    const promiseOne = new Promise(function(resolve , reject){
    //  Do an async task
    // DB calls // cryptography // network
    setTimeout(function(){
        console.log("Async task is complete");
        resolve()
    },1000)
})

// .then() connects resolve to this function
promiseOne.then(function(){
    console.log("Promise consumed");
})


new Promise(function(resolve , reject){
    setTimeout(function(){
        console.log("Async task 2");
        resolve()
    },1000)
    
}).then(function(){
    console.log("Async 2 resolved");
})


const promiseThree = new Promise(function(resolve , reject){
    setTimeout(function(){
        resolve({username : "Ankur",
                emailId : "ankur@google.com"})
    },1000)
})

promiseThree.then(function(user){
    console.log(user);
})

promiseFour = new Promise(function(resolve, reject){
    setTimeout(function(){
        let error = false;   // true =>  catch error
        if(!error){
            resolve({username : "Ankur", password : 123})
        }else{
            reject('ERROR : Something went wrong')
        }
    },1000)
})

promiseFour.then((user)=>{
    console.log(user);
    return user.username
}).then((username)=>{
    console.log(username);
}).catch((error)=>{
    console.log(error);
}).finally(()=>{
    console.log('The promise is either resolved or rejected');
})

const promiseFive = new Promise(function(resolve, reject){
    setTimeout(function(){
        let error = true;   // true =>  catch error
        if(!error){
            resolve({username : "JS", password : 123})
        }else{
            reject('ERROR : JS went wrong')
        }
    },1000)
})


// async function consumePromiseFive(){
//     const response = await promiseFive
//     console.log(response)
// }

async function consumePromiseFive(){
    try {
        const response = await promiseFive
        console.log(response);
    } catch (error) {
        console.log(error);
    }
}

consumePromiseFive()



// async function getAllUsers(){
//     try {
//         const response =  await fetch('https://jsonplaceholder.typicode.com/users')
//         const data = await response.json()
//         console.log(data);
//     } catch (error) {
//         console.log("E:" , error);
//     }
// }

// getAllUsers()


fetch('https://jsonplaceholder.typicode.com/users')
.then((response) => {
    return response.json()
})
.then((response) => console.log(response))
.catch((error) => console.log("E :", error))
</script>
</html>